language: python
python:
  - "2.7"

install:
  - "pip install pycurl"
  - "sudo useradd shinken"
  - "pip install -r requirements.txt"

script: nosetests -vx --with-coverage --cover-package=module

after_success:
  coveralls

notifications:
  email: false
